### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [sebastian-13/ProyectoFinalBioinf2017-II#1]
Suena bien, pero dado que estamos en el equipo oyamel, me gustaría que específicaras por qué crees que estos tipos de datos y análisis ayudarán a tu proyecto en concreto.

Cuida tu formato md, creo que intentaste poner viñetas en vez de código.

**Comment by AzaleaGuerra** [comment]
Suena bien. Recuerda revisar cómo se ve en github lo que subas.
Quizá podrías hacer algo más que genética de poblaciones, como detectar firmas de selección.

**Comment by sebastian-13** [comment]
Ok, muchas gracias =)
