### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [sebastian-13/ProyectoFinalBioinf2017-II#2]
Está bien que aprendas a utilizar estas herramientas, pero creo que tienes que enfocarte en algo específico de todo lo que mencionaste o no creo que te de tiempo.

¿Ya instalaste y probaste con los datos del tutorial de Stacks que este funcione? Este paso NO es trivial y puede retrasarte semanas. 

Está mal puesto el enlace a tus avances 2 en el listado de proyectos, corrígelo por favor.

**Comment by sebastian-13** [comment]
Ok gracias !
